Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/produtos/urls.py
from django.urls import path
from . import views
from produtos.views import TelaCadastroProduto, TelaListaProdutos

app_name = 'produtos'

urlpatterns = [
    path('', TelaListaProdutos.as_view(), name="produtos"),
    path('cadastro/', TelaCadastroProduto.as_view(), name='cadastro_produtos'),
    path('cadastro/ajax/busca_preco/', views.buscaPreco, name='busca_preco'),
    path('ajax/adiciona_produto/', views.adicionaProduto, name='adiciona_produto'),
]

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/siteMonitora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from users import views as user_views
from produtos import views as produto_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', produto_views.index, name='index'),
    path('produto/', include('produtos.urls')),
    path('login/', user_views.entrar, name='entrar'),
    path('cadastro/', user_views.cadastrar, name='cadastrar'),
    path('logout/', user_views.sair, name="sair"), 
    path('painel/', include('users.urls')), 
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/users/urls.py
from django.urls import path
from . import views as user_views
from produtos import views as prod_views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('detalhes/', user_views.painel, name="painel"),
    path('produto/ajax/delete_prod/', prod_views.deleteProd, name="deleteProd"),
    path('produto/', user_views.painelProdutos, name="painel_produtos"),
    path('<int:id_produto>', prod_views.detalheProduto, name="detalhe_prod"),
    path('ajax/delete_prod/', prod_views.deleteProd, name='deleteProd'),
]

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/produtos/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
import json

class Produto(models.Model):

    objects = models.Manager()

    unique_id = models.CharField(max_length=100, null=True)
    id_produto = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=512)
    descricao = models.TextField()
    url = models.TextField(blank=True)
    preco_atual = models.TextField(null=True)
    data_cadastro = models.DateTimeField(default=timezone.now, blank=True)
    tempo_notificacao = models.IntegerField(default=30, blank=True)
    user = models.ManyToManyField(User)

    def __str__(self):
        """String for representing the Model object."""
        return self.nome
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('product-detail', args=[str(self.id_produto)])


class HistoricoPreco(models.Model):

    objects = models.Manager()

    id_historico = models.AutoField(primary_key=True)
    data = models.DateTimeField(default=timezone.now, blank=True)
    preco = models.TextField()
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)

    def __str__(self):
        """String for representing the Model object."""
        str(self.data)
        return str
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('hist-detail', args=[str(self.id_historico)])

class Notificacao(models.Model):
    objects = models.Manager()

    id_notificacao = models.AutoField(primary_key=True)
    vista = models.BooleanField(default=0)
    data = models.DateTimeField(default=timezone.now, blank=True)
    mensagem = models.TextField()
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)
    user = models.ManyToManyField(User)




Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/users/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Usuario(models.Model):

    objects = models.Manager()

    id_usuario = models.AutoField(primary_key=True)
    telefone = models.CharField(max_length=32)
    data_nascimento = models.DateField()
    email = models.EmailField(max_length=128)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def parseBirthday (self):
        birthday = self.data_nascimento.strftime('%Y-%m-%d')
        return birthday

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/produtos/forms.py
from django.forms import ModelForm
from django import forms
from produtos.models import Produto
    
class SortProdForm(forms.Form):
    nome = forms.CharField(label= False, required= True, widget=forms.TextInput(attrs={'class': 'form-control mr-sm-2', 'placeholder': 'Buscar', 'required' : True}))

class CadastroProdForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'tempo_notificacao', 'preco_atual', 'url']
        widgets = {
            'url' : forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255, 'required': True, 'placeholder': "URL"}),
            'preco_atual': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255, 'required': True,}),
            'nome': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255, 'required': True, 'placeholder': "Nome do produto"}),
            'tempo_notificacao': forms.NumberInput(attrs={'class': 'form-control', 'max': '3600', 'min': '5', 'required': False, 'null': True, 'blank': True}),
        }

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/produtos/views.py
from django.shortcuts import render, redirect
from produtos.models import Produto, HistoricoPreco, Notificacao
from produtos.forms import SortProdForm, CadastroProdForm
from uuid import uuid4
from urllib.parse import urlparse
from django.core import serializers
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.views.decorators.http import require_POST, require_http_methods
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.utils import timezone
from datetime import timedelta
import pytz
import json
import re
import requests
from bs4 import BeautifulSoup, NavigableString
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
import apscheduler

scheduler = BackgroundScheduler()
scheduler.start()
scheduler.print_jobs()



def index(request):
    produtos = Produto.objects.all().order_by('data_cadastro')
    return render(request, 'indexteste.html', {'produtos': produtos})


class TelaListaProdutos(View):
    context = dict.fromkeys(['produtos_user', 'produtos', 'sort_form'])

    @csrf_exempt
    def post(self, request):
        sort_form = SortProdForm(request.POST)

        if sort_form.is_valid():
            produtos = Produto.objects.all().filter(nome=request.POST['nome'])
            self.context['produtos'] = produtos
            self.context['sort_form'] = sort_form

            return render(request, 'produtos.html', self.context)

    def get(self, request):
        self.context['sort_form'] = SortProdForm()
        try:
            self.context['produtos_user'] = Produto.objects.all().filter(user=request.user)
            self.context['produtos'] = Produto.objects.all().exclude(user=request.user).order_by('data_cadastro')
        except TypeError:
            self.context['produtos'] = Produto.objects.all().order_by('data_cadastro')
        return render(request, 'produtos.html', self.context)

@csrf_exempt
def buscaPreco(request):
    url = request.POST.get("url")

    if not url:
        messages.error(request, "URL Inválida")
        return JsonResponse({'Error': 'URL Inválida'})

    if not is_valid_url(url):
        messages.error(request, "URL Inválida")
        return JsonResponse({'Error': 'URL Inválida'})

    preco_produto = getProdutoInfos(url)

    print(preco_produto['preco'])

    if preco_produto['erro']:
        messages.error(request, preco_produto['erro'])
        return JsonResponse({'Error': preco_produto['erro']})
        
    jsonData = { 
        'url': url,
        'preco_produto': preco_produto['preco'][0],
        }

    return JsonResponse(jsonData)

        
class TelaCadastroProduto(View):

    context = dict.fromkeys(['produtos_user', 'url_form', 'sort_form', 'cadastro_form', 'produto', 'preco']) 

    @csrf_exempt
    def post(self, request):

        self.context['produtos_user'] = Produto.objects.all().filter(user=request.user)
        self.context['prod_form'] = CadastroProdForm()
        prod_form = CadastroProdForm(request.POST)

        if prod_form.is_valid:
            
            url = request.POST.get('url')

            if not url:
                messages.error(request, "URL Inválida")
                return render(request, 'cadastro_produto.html', self.context)

            if not is_valid_url(url):
                messages.error(request, "URL Inválida")
                return render(request, 'cadastro_produto.html', self.context)

            produto = Produto()
            produto.url = request.POST.get("url")
            produto.preco_atual = request.POST.get("preco_atual")
            produto.nome = request.POST.get("nome")
            produto.tempo_notificacao = request.POST.get("tempo_notificacao")

            print("other one " + str(produto.preco_atual))

            try:
                salvaProdutoBD(produto, request.user)
                hist = HistoricoPreco()
                hist.preco = produto.preco_atual
                hist.produto = produto
                hist.save()
                print("atualizou")

                # Adiciona uma tarefa agendada para o produto, 
                # que atualiza o preço do produto de acordo com o 
                # tempo definido pelo usuário
                global scheduler
                scheduler.add_job(
                    atualizaPreco, 'interval', 
                    minutes=int(produto.tempo_notificacao), 
                    args=(produto, ), 
                    id=str(produto.id_produto),
                )

                self.context['produtos_user'] = Produto.objects.all().filter(user=request.user)
                messages.success(request, "Produto cadastrado na sua lista")

                return render(request, 'cadastro_produto.html', self.context)

            except Exception as e:
                messages.error(request, e)
                return render(request, 'cadastro_produto.html', self.context)

            
    def get(self, request):

        self.context['produtos_user'] = Produto.objects.all().filter(user=request.user).order_by('data_cadastro')
        self.context['prod_form'] = CadastroProdForm()
        return render(request, 'cadastro_produto.html', self.context)


def is_valid_url(url):
    validate = URLValidator()
    try:
        validate(url)  # check if url format is valid
    except ValidationError:
        return False

    return True


def getProdutoInfos(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'}
    result = requests.get(url, headers=headers)
    data_set = dict(url=url, nome=[], preco=[], descricao=[], erro=[])
    
    if result:
        print("Procurando preço...")
        produto_infos = {
            # "nome": ['name', 'nome', 'title'],
            "preco": ['price', 'preco', 'valor', 'value', 'Valor'],
            # "descricao": ['description', 'descricao', 'about'],
        }

        tags = ['meta', 'span', 'strong', 'h1', 'h2', 'h3', 'p']
        properties = ['itemprop', 'name', 'content', 'class', 'id']

        soup = BeautifulSoup(result.text, "html.parser")

        for key, values in produto_infos.items():
            for tag in tags:
                for prop in properties:
                    for value in values:
                        if (soup.find_all(tag, attrs={prop: re.compile(value)})):
                            for data in soup.find_all(tag, attrs={prop: re.compile(value)}):
                                if data.find_all(text=True):
                                    text = data.get_text()
                                    print(text)
                                else:
                                    text = data.get('content')
                                    print(text)

                                if text is not None:
                                    if isPrice(text):
                                        data_set[key].append(text)

                                   

            print(key + " ===== ")
            print(data_set[key])
            if not data_set[key]:
                data_set['erro'] = "Não conseguimos encontrar o preço do produto :/"

    else:
        data_set['erro'].append("Não conseguimos entrar em contato com a URL :/")

    return data_set

def salvaProdutoBD(produto, user):
    produto.save()
    produto.user.add(user)


def isPrice(text):
    return re.match(r"^(R\$|\$)?\s?(\d{1,3}([.,]]\d{3})*|(\d+))([.,]\d{2})?$", text)

@csrf_exempt
def adicionaProduto(request):
    user = request.user
    produto = Produto.objects.get(id_produto=request.POST['produto_id'])
    produto.user.add(user)
    json = {'success': 'Success'}
    return JsonResponse(json)

def atualizaPreco(produto):
    p = Produto.objects.get(id_produto=produto.id_produto)
    print("Atualizando produto " + str(p.id_produto))
    novo_preco = getProdutoInfos(p.url)

    p.preco_atual = novo_preco['preco'][0]
    p.save()

    hist = HistoricoPreco()
    hist.preco = novo_preco['preco'][0]
    hist.produto = p
    hist.data = timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone())
    hist.save()

def addNotificacao(produto):
    notif = Notificacao()
    notif.produto = produto
    msg = "Novo preco: " + produto.preco_atual
    notif.mensagem = msg
    notif.save()
    print(produto.user.all())
    for user in produto.user.all():
        notif.user.add(user)
    


@csrf_exempt
def deleteProd(request):
    try:
        print(request.POST.get('id_produto'))
        produto = Produto.objects.get(id_produto=request.POST['id_produto'])
        if produto.user.count() == 1:
            global scheduler
            scheduler.remove_job(str(produto.id_produto))
            produto.delete()    
        else: 
            produto.user.remove(request.user)
        
        json = {'success': 'Produto removido!'}
            
    except Produto.DoesNotExist:
        json = {'error': "Desculpe, houve um problema"}
    except apscheduler.jobstores.base.JobLookupError:
        produto.delete() 
        json = {'success': 'Produto removido!'}

    return JsonResponse(json)

def detalheProduto(request, id_produto):
    context = {}

    if request.method == 'POST':
        produto = Produto.objects.get(id_produto = id_produto)
        produto.nome = request.POST['nome']
        produto.tempo_notificacao = request.POST['tempo_atualizacao']
        produto.save()
        try:

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block title %}<title>Monitora</title>{% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan|Cabin|Abel|Livvic|Righteous|Montserrat&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
</head>

<body>

  {% block nav %}
  <nav class="navbar navbar-expand-lg navbar-dark justify-content-between">
    <p class="navbar-brand">MONITORA</p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span data-feather="menu"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active" id="navLink-Inicio">
          <a class="nav-link nav-links" href="{% url 'index' %}">INÍCIO</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link nav-links dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            PRODUTOS
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'produtos:cadastro_produtos' %}">Cadastrar produto</a>
            <a class="dropdown-item" href="{% url 'user:painel_produtos' %}">Meus produtos monitorados</a>
            <a class="dropdown-item" href="{% url 'produtos:produtos' %}">Todos os produtos</a>
          </div>
        </li>
       
        <li class="nav-item" id="navLink-Sobre">
          <a class="nav-link nav-links" href="#">SOBRE</a></a>
        </li>
      </ul>

      <ul class="navbar-nav btn-login">
          {% if user.is_authenticated %}
        
        <li class="nav-item dropdown" id="user-item">
          <a class="nav-link nav-links dropdown-toggle" href="#" id="navbarDropdown-user" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span data-feather="user"></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" id="dropdown-menu-user">
            <a class="dropdown-item" href="{% url 'user:painel' %}">Minha Conta</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'sair' %}">Sair</a>
          </div>
        </li>
        {% else %}
        <a class="nav-link nav-links navbar-right" href="{% url 'entrar' %}">ENTRAR</a>
        {% endif %}
        </li>
      </ul>
    </div>
  </nav>
  {% endblock %}


  {% block content %} {% endblock %}


  <script type="text/javascript" src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/feather.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/Chart.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/custom.js' %}"></script>
</body>

</html>

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/templates/cadastro.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %} <title>Monitora - Cadastro</title> {% endblock %}


{% block content %}
<div class="esquerda">
</div>
<div class="container-fluid jumbotron formulario cadastro">
    {% if messages %}
    <div class="container-fluid col-10">
        {% for message in messages%}
      <div class="alert {{ message.tags }} col-12 ">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
        <span data-feather="alert-circle" id="alert-icon"></span>
        
        {{ message }}
        
        </div>
        {% endfor %}
      
    </div>
    {% endif %}

  <div class="row justify-content-center">
    <h2>Cadastro</h2>
  </div>

  <hr class="my-3">

  <form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
      <label>Nome</label>
      {{ form.first_name }}
    </div>
    <div class="form-group">
      <label>Sobrenome</label>
      {{ form.last_name }}
    </div>
    <div class="form-group">
      <label>Email</label>
      {{ usuario_form.email }}
    </div>
    <div class="form-group">
      <label>Telefone</label>
      {{ usuario_form.telefone }}
    </div>
    <div class="form-group">
      <label>Data de nascimento</label>
      {{ usuario_form.data_nascimento }}
    </div>
    <div class="form-group">
      <label>Nome de Usuário</label>
      {{ form.username }}
    </div>
    <div class="form-group">
      <label>Senha</label>
      {{ form.password }}
    </div>
    <hr class="my-3">
    <div class="row justify-content-center">
      <button class="btn button-custom" style="width: 300px" type="submit">Confirmar</button>
    </div>
  </form>

</div>
{% endblock %}

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/templates/cadastro_produto.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %} <title>Monitora - Cadastro de Produto</title> {% endblock %}

{% block content %}
<div class="container-fluid produtos-page">

    <div class="container-fluid row row-produtos produtos">
        <div class="container" id="messages">
        {% if messages %}
            {% for message in messages%}
            <div class="alert {{ message.tags }} col">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                <span data-feather="alert-circle" id="alert-icon"></span>

                {{ message }}

            </div>
            {% endfor %}

        {% endif %}
    </div>
        <div class="jumbotron jumbotron-prod-form" id="url_form">
                
            <h1 class="display-4">Monitorar produto</h1>
            
            <p class="lead">Insira a URL do produto a ser monitorado</p>

            <hr class="my-3">

                {{ prod_form.url }}
                <br>
                <button class="btn button-outline-custom btn-lg" role="button" 
                                    id="busca_produto">Buscar
                    <span data-feather="search" id="search-icon"></span></button>
            <br>
            <br>
            <div class="spinner-border" role="status" id="loading">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <div class="jumbotron jumbotron-prod-form" id="confirma_cadastro_form" style="display: none;">
            <h1 class="display-4">Cadastrar produto</h1>
            <hr class="my-3">
            <form method="POST" id="prod-search-form">
                {% csrf_token %}
                <label for="id_url">URL</label>
                {{ prod_form.url }}

                <label for="id_nome">Nome produto </label>
                {{ prod_form.nome }}
                
                <label for="id_preco_atual">Preço</label>
                {{ prod_form.preco_atual }}
                
                <label for="id_tempo_notificacao">Tempo de atualização (min)</label>
                {{ prod_form.tempo_notificacao }}
                <br>
                <button class="btn button-outline-custom btn-lg" role="button" type="submit"
                    id="prod-search-btn">Monitorar
                    <span data-feather="search" id="search-icon"></span></button>
            </form>
            <br>
        </div>
        <div class="page-title">
            <h3 class="title">Seus produtos: </h3>
        </div>
        <div class="row justify-content-center produtos-display">
            
            {% for prod_user in produtos_user %}
            <div class="card card-expandable" id="{{ prod_user.id_produto }}">
        
        
                <div class="card-body">
                    <a href="{{ prod_user.url }}" target="_blank" 
                        class="urllink" title="Ir para o site">
                        <span data-feather="external-link"></span></a>

                    <h2 class="card-text-descricao">{{prod_user.nome}}</h2>
                    <p class="card-text-preco">{{prod_user.descricao}}</p>
                    <div class="row justify-content-around card-btn">
                        <a href="{% url 'user:detalhe_prod' prod_user.id_produto %}" 
                        class="btn button-outline-custom"><span data-feather="plus-circle"></span>
                         Detalhes</a>
                    </div>
                </div>
                <div class="card-title">
                    <h5 class="card-text-title">Preço atual: {{prod_user.preco_atual}}</h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>

    <!-- MODAL -->
    
{% endblock %}

Monitora - Aplicação WEB para monitorar preços - Web Scrapping/Fontes/siteMonitora/templates/usuario.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %}
<title>Monitora - Conta</title>
{% endblock %}

{% block content %}
<div class="container-fluid usuario">
    <div class="sidebar-user">
        <div class="list-group">
            <a class="btn list-group-item active" id="button-detalhes" href=""><span data-feather="user"
                    class="sidebar-icon"></span>Dados pessoais</a>
            <a class="btn list-group-item" id="button-produto" href="{% url 'user:painel_produtos' %}">
                <span data-feather="package" class="sidebar-icon"></span>Produtos cadastrados</a>
        </div>
    </div>
    <div class="user-details">
            <div class="container" id="messages">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert {{ message.tags }} col">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                            <span data-feather="alert-circle" id="alert-icon"></span>
            
                            {{ message }}
            
                        </div>
                        {% endfor %}
            
                    {% endif %}
                </div>
        <div class="detalhes-user">
            <div id="userheader" class="nav row user-header ">
                <div class="user-image">
                    <img id="user-image" src="{% static 'images/perfilzao.jpg' %}">
                </div>
                <div class="col user-name">
                    <h1 class="h1">{{ user.first_name }} {{ user.last_name }}</h1>
                    <p class="lead"> {{ usuario.email }}</p>
                </div>
            </div>
            <div id="userbody" class="user-body">
                <div class="label row justify-content-between">
                    <label>Informações Pessoais </label>
                    <button class="btn button-outline-custom button-page-user" data-toggle="modal"
                        data-target="#userInfoModal">Editar</button>
                </div>
                <div class="info justify-content-center">
                    <div class="container-fluid info col-5">
                        <div class="row">
                            <div class="col-4"><b>Nome </b></div>
                            <div class="col-6">{{ user.first_name }} {{ user.last_name }}</div>
                        </div>
                        <hr class="my-2">
                        <div class="row">
                            <div class="col-4"><b>Email </b></div>
                            <div class="col-6">{{ usuario.email }}</div>
                        </div>
                        <hr class="my-2">
                        <div class="row">
                            <div class="col-4"><b>Telefone </b></div>
                            <div class="col-6">{{ usuario.telefone }}</div>
                        </div>
                        <hr class="my-2">
                        <div class="row">
                            <div class="col-4"><b>Data de Nascimento </b></div>
                            <div class="col-6">{{ usuario.data_nascimento }}</div>
                        </div>
                        <hr class="my-2">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- MODAIS -->
<div class="modal fade" id="userInfoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Informações Pessoais</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Nome</label>
                        <input type="text" class="form-control loginInput cadastroInput" value="{{ user.first_name }}"
                            id="id_first_name" name="first_name" required>
                    </div>
                    <div class="form-group">
                        <label>Sobrenome</label>
                        <input type="text" class="form-control loginInput cadastroInput" value="{{ user.last_name }}"
                            id="id_last_name" name="last_name" required>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control loginInput cadastroInput" value="{{ usuario.email }}"
                            id="id_email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label>Telefone</label>
                        <input type="text" class="form-control loginInput cadastroInput" value="{{ usuario.telefone }}"
                            id="id_telefone" name="telefone" required>
                    </div>
                    <div class="form-group">
                        <label>Data de nascimento</label>
                        <input type="date" class="form-control loginInput cadastroInput"
                            value="{{ usuario.parseBirthday }}" id="id_data_nascimento" name="data_nascimento" required>
                    </div>
                    <button type="submit" class="btn button-outline-custom">Salvar alterações</button>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>


{% endblock %}